spring:
  application:
    name: gateway-service

  # local 환경 실행 기분
  profiles:
    default: local

  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/user/** # /users/** 경로로 들어오는 요청을 이 라우트로 처리

        discovery:
          locator:
            enabled: true


