server:
  port: 19005

spring:
  application:
    name: order-service

  config:
    import: optional:file:./.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: order
    password: order1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: order_schema

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}
    service-url:
      defaultZone: http://localhost:8761/eureka