spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA:delivery_schema}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}