spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/msa
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: delivery_schema

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka